#-------------------------------
# General Site Settings
title: Farseers Devlogs
logo: /images/LogoWhite.png
description: here is farseers devBlog.
baseurl: ""
url: #"https://joseph-jekyll.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Farseers
  bio: Update DevLogs
  avatar: '/images/LogoFitWhite.png'

social:
- {icon: "ion ion-logo-github", label: Github, link: "https://github.com/faarseer"}
- {icon: "ion-logo-instagram", label: Instagram, link: "https://instagram.com"}
- {icon: "ion-logo-twitter", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", label: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-discord", label : Discord, link:""}
#- {icon: "ion-logo-pinterest", label: Pinterest, link: "https://pinterest.com"}
#- {icon: "ion-logo-dribbble", label: Dribbble, link: "https://dribbble.com"}
#- {icon: "ion ion-logo-vimeo", label: Vimeo, link: "https://vimeo.com"}
# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: FARSEERS DEVBlOG
  hero__description: Unity GameDevelop
  hero__image: '/images/LogoFitWhiteTP.png'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: false # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Get fresh news # Add your Title
mailchimp__text: Subscribe to my newsletter and I’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact: +821075579074
email: 31futhark@gmail.com
description: Farseers Game Studio

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: farseers # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/page/:num-1"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass

  style: compressed
